### ISSUE TITLE
Scroll/zoom not working properly in Firefox

### ISSUE THREAD

**Issue by impressivewebs** [PavelLaptev/warp-svg#3]
Using the scroll option on the mouse is supposed to zoom in or out depending on if you scroll up or down. This works fine in Chrome but in Firefox the zoom always zooms out, even if you scroll the other direction.

Tested in latest stable Firefox (v79) on Windows 10 and latest stable Brave and Chrome on Win10.

**Comment by PavelLaptev** [comment]
@impressivewebs thank you! I didn't test the scroll properly. Will fix it this weekend ;-)

**Comment by PavelLaptev** [comment]
@impressivewebs zoom fixed 😉

**Comment by impressivewebs** [comment]
Nice! Looks good now. Do you mind if I ask, what exactly was the problem? Why was Firefox handling this differently? Is there some DOM method you were using that wasn't working properly?

**Comment by PavelLaptev** [comment]
Sure @impressivewebs :-) The reason was in `wheelDelta` — FireFox deprecated this event prop, so I changed it to `deltaY` to track if its a zoomin or zoomout. 
https://stackoverflow.com/questions/16788995/mousewheel-event-is-not-triggering-in-firefox-browser
